@if($errors->any())<div class="cms-errors"><strong>Periksa kembali data berikut:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="cms-editor-grid"><div class="cms-editor-main">
<div class="cms-panel"><h2>Konten Artikel</h2><div class="cms-fields"><label><span>Judul Artikel *</span><input type="text" name="title" value="{{ old('title',$post->title) }}" required data-post-title><small>Slug dan alt gambar dibuat otomatis dari judul.</small></label><label><span>Ringkasan</span><textarea name="excerpt" rows="3" maxlength="1000">{{ old('excerpt',$post->excerpt) }}</textarea></label><div class="cms-rich-field"><span>Isi Artikel *</span><div class="cms-editor-toolbar" role="toolbar" aria-label="Format artikel"><button type="button" data-command="formatBlock" data-value="p">Paragraf</button><button type="button" data-command="formatBlock" data-value="h2">H2</button><button type="button" data-command="formatBlock" data-value="h3">H3</button><button type="button" data-command="bold"><b>B</b></button><button type="button" data-command="italic"><i>I</i></button><button type="button" data-command="insertUnorderedList">List</button><button type="button" data-command="formatBlock" data-value="blockquote">Quote</button><button type="button" data-command="createLink">Link</button></div><div class="cms-rich-editor" contenteditable="true" data-rich-editor>{!! old('content',$post->content) !!}</div><textarea class="cms-rich-source" name="content" required data-rich-source>{{ old('content',$post->content) }}</textarea><small>Tulis langsung seperti editor dokumen. Gunakan H2/H3 untuk struktur SEO.</small></div></div></div>
<div class="cms-panel"><h2>SEO Search Engine</h2><div class="cms-seo-preview"><small>Preview hasil pencarian</small><strong>{{ old('meta_title',$post->meta_title) ?: old('title',$post->title ?: 'Judul artikel akan tampil di sini') }}</strong><em>https://unguspa.com/artikel/{{ old('slug',$post->slug ?: 'slug-artikel') }}</em><p>{{ old('meta_description',$post->meta_description) ?: old('excerpt',$post->excerpt ?: 'Meta description artikel akan tampil di bagian ini.') }}</p></div><div class="cms-fields cms-fields-two"><label><span>SEO Title</span><input type="text" name="meta_title" maxlength="255" value="{{ old('meta_title',$post->meta_title) }}"></label><label><span>Focus Keyword</span><input type="text" name="focus_keyword" value="{{ old('focus_keyword',$post->focus_keyword) }}"></label><label class="cms-span-two"><span>Meta Description</span><textarea name="meta_description" rows="3" maxlength="320">{{ old('meta_description',$post->meta_description) }}</textarea></label></div></div>
</div><aside class="cms-editor-side">
<div class="cms-panel"><h2>Publikasi</h2><div class="cms-fields"><label><span>Status</span><select name="status"><option value="draft" @selected(old('status',$post->status ?: 'draft')==='draft')>Draft</option><option value="published" @selected(old('status',$post->status)==='published')>Published</option></select></label><label><span>Tanggal Publikasi</span><input type="datetime-local" name="published_at" value="{{ old('published_at',$post->published_at?->format('Y-m-d\TH:i')) }}"></label><button class="cms-save" type="submit">Simpan Artikel</button><a class="cms-cancel" href="{{ route('admin.posts.index') }}">Batal</a></div></div>
</aside></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const editor=document.querySelector('[data-rich-editor]'),source=document.querySelector('[data-rich-source]'),form=editor?.closest('form');
 document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('click',()=>{let value=button.dataset.value||null;if(button.dataset.command==='createLink')value=prompt('Masukkan URL link:','https://');if(button.dataset.command==='createLink'&&!value)return;document.execCommand(button.dataset.command,false,value);editor.focus();source.value=editor.innerHTML;}));
 editor?.addEventListener('input',()=>source.value=editor.innerHTML);form?.addEventListener('submit',()=>source.value=editor.innerHTML);
});
</script>
